name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv
        run: python3 -m venv .venv

      - name: Install uv
        run: pip install uv

      - name: Sync deps
        run: uv sync

      - name: Run bot test
        env:
          ANNOUNCE_CHANNEL_ID: ${{ secrets.ANNOUNCE_CHANNEL_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          PREFIX: ${{ secrets.PREFIX }}
        run: |
          . .venv/bin/activate
          python main.py &
          BOT_PID=$!
          sleep 60
          if ps -p $BOT_PID > /dev/null; then
              echo "✅ Bot started successfully"
              kill $BOT_PID
              exit 0
          else
              echo "❌ Bot failed to start"
              exit 1
          fi
